"""empty message

Revision ID: 560db6485717
Revises: 
Create Date: 2019-08-21 10:58:49.169067

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '560db6485717'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asn',
    sa.Column('asn', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('as_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('asn')
    )
    op.create_table('community',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prefix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asn_id', sa.Integer(), nullable=False),
    sa.Column('asn_path', postgresql.ARRAY(sa.Integer(), dimensions=1), nullable=True),
    sa.Column('prefix', postgresql.CIDR(), nullable=False),
    sa.Column('next_hops', postgresql.ARRAY(postgresql.INET(), dimensions=1), nullable=True),
    sa.Column('neighbor', postgresql.INET(), nullable=True),
    sa.Column('ixp', sa.String(length=255), server_default='N/A', nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('age', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asn_id'], ['asn.asn'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prefix_communities',
    sa.Column('prefix_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.ForeignKeyConstraint(['prefix_id'], ['prefix.id'], ),
    sa.PrimaryKeyConstraint('prefix_id', 'community_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prefix_communities')
    op.drop_table('prefix')
    op.drop_table('community')
    op.drop_table('asn')
    # ### end Alembic commands ###
