"""add index for filtering prefixes by IPv4 / IPv6 address family

Revision ID: e2fb90cb7142
Revises: f7649cb51cf2
Create Date: 2020-04-25 11:15:12.271848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy import text

from lg.models import Prefix

revision = 'e2fb90cb7142'
down_revision = 'f7649cb51cf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute("CREATE INDEX ON prefix USING gist (prefix inet_ops);")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('idx_prefix1_cidr', table_name='prefix')
    op.drop_index('prefix_prefix_idx', table_name='prefix')
    # ### end Alembic commands ###
    pass
