"""add indexes for prefix asn_id, prefix, and last_seen

Revision ID: f7649cb51cf2
Revises: 560db6485717
Create Date: 2020-04-25 10:24:27.266448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7649cb51cf2'
down_revision = '560db6485717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_prefix_asn_id'), 'prefix', ['asn_id'], unique=False)
    op.create_index(op.f('ix_prefix_last_seen'), 'prefix', ['last_seen'], unique=False)
    op.create_index(op.f('ix_prefix_prefix'), 'prefix', ['prefix'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prefix_prefix'), table_name='prefix')
    op.drop_index(op.f('ix_prefix_last_seen'), table_name='prefix')
    op.drop_index(op.f('ix_prefix_asn_id'), table_name='prefix')
    # ### end Alembic commands ###
